{% set name = "transitions" %}
{% set version = "0.8.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ff7a3bfa4ac64b62993bb19dc2bb6a0ccbdf4e70b2cbae8350de6c916d77748

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - six
  run:
    - python
    - six

test:
  source_files:
    - examples
    - tests
  requires:
    - dill
    - mock
    - pytest
    - pytest-cov
    - pycodestyle
    - pygraphviz  # [not win]
    - python-graphviz
    - pip
  imports:
    - transitions
  commands:
    - python -m pip check
    - pytest --pyargs -k "not conformance" --cov transitions

about:
  home: https://github.com/pytransitions/transitions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lightweight, object-oriented finite state machine implementation in Python

extra:
  recipe-maintainers:
    - bollwyvl
