{% set name = "transitions" %}
{% set version = "0.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b5712bc1ef3854ff3104cd22502e2ce66c1da5b9ace90427b97bd9b7efd921fa

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six

test:
  source_files:
    - examples
    - tests
  requires:
    - dill
    - mock
    - nose
    - pycodestyle
    - pygraphviz  # [not win]
  imports:
    - transitions
  commands:
    - nosetests

about:
  home: https://github.com/pytransitions/transitions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A lightweight, object-oriented finite state machine implementation in Python'

extra:
  recipe-maintainers:
    - bollwyvl
