{% set name = "transitions" %}
{% set version = "0.8.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e441c66a0c753d56c01c3e5e547f21dbe4a5569c939f12477475c5e81d79769b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - six
  run:
    - python >=2.7
    - six

test:
  source_files:
    - examples
    - tests
  requires:
    - dill
    - mock
    - pytest
    - pytest-cov
    - pycodestyle
    - pygraphviz  # [not win]
    - python-graphviz
    - pip
  imports:
    - transitions
  commands:
    - python -m pip check
    - pytest --pyargs -k "not conformance" --cov transitions

about:
  home: https://github.com/pytransitions/transitions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lightweight, object-oriented finite state machine implementation in Python

extra:
  recipe-maintainers:
    - bollwyvl
