travis:
  secure:
    BINSTAR_TOKEN: dYMM5RysGmUjEYQ3b/zVjOogEz2+2kMaf/dSJiZ0VvgPjpY55hmGybHJIDrFpeILYsTv4ODDhMwG10TelTMRNkdb8xM1ga316vbI9HQSryutmyGzreUrFTZ1aygu9Cn3zM2iJL/Gd4iSwbpK9fKKDRBLIoySIRLCM/YbTCZmScjq3VzA7wLof7buXe2Q4Ym9NjcKonzmoDQp75qRYZg8qNFj8yhJ6E1NMWWtToYe1Dc6sD6JhhTR4vkVUhhZfn6anNwneaNho/L9ZTXCInRqNSZtNUQTpC+c0yb31wJ5PMN3lrPtC+NqrzOwx88wSCFlKxIAqofZJ1h3gThPK0iZWI0xp5WCIfNY1u97oyAy14sHSjVR2FcShF0lSL34nYmEjJSol8pol8r6jMhUizDvqj6k7TQHdWKt3airZ7gI2MUB+LeumMcSrn6hUzRmLbbYe1XKSzCs9rzmDAXp2pl6MyhhKmsXRy5hSV/XV+6rkbxKWl1KXzGQglDATFSObnS8ofxYuaCLYT3IybKmQmTpPP290Xcu4+XoV89b5xROGW4wrYSRzyyZT2YSIulX+TM+y2JTaW82kkPylYqR15gBy8juLsNzl/YbLKy6R3S0Tne6kFiei8xvBxNfZIHbWzkHR4/rFi620aZuZ7vTRnbbcVQR+YPyM8DvKTERkO0xs68=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
